name: Linux Release
permissions:
  contents: write

on:
  workflow_dispatch:
  push:

jobs:
  linux-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.18.0'

      - name: Build
        run: go build -ldflags "-s -w -linkmode external -extldflags -static" -o coze-discord-proxy

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coze-discord-proxy
          path: coze-discord-proxy

      - name: Generate release tag
        id: gen_tag
        run: |
          echo "::set-output name=release_tag::Build_v$(date +"%Y%m%d_%H%M%S")"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: coze-discord-proxy
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.gen_tag.outputs.release_tag }}
